name: Notify When Maintainers Cannot Edit

# **What it does**: Notifies the author of a PR when their PR does not allow maintainers to edit it.
# **Why we have it**: To prevent having to do this manually.
# **Who does it impact**: Maintainers, contributors.

on:
  pull_request_target:
    types:
      - opened
  workflow_call:

jobs:
  notify-when-maintainers-cannot-edit:
    if: github.repository_owner == 'zachwatkins'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `
              query($number: Int!) {
                repository(owner: '${context.repo.owner}', name: '${context.repo.repo}') {
                  pullRequest(number: $number) {
                    headRepositoryOwner {
                      login
                    }
                    maintainerCanModify
                    state
                  }
                }
              }
            `;

            const pullNumber = context.issue.number;
            const variables = { number: pullNumber };

            try {
              console.log(`Check ${context.repo.owner}/${context.repo.repo}#${pullNumber} for maintainer edit access ...`);

              const result = await github.graphql(query, variables);

              console.log(JSON.stringify(result, null, 2));

              const pullRequest = result.repository.pullRequest;

              if (pullRequest.headRepositoryOwner.login === context.repo.owner) {
                console.log(`PR owned by ${context.repo.owner}`);
                return;
              }

              if (pullRequest.state !== 'OPEN') {
                console.log('PR has already been closed or merged');

                return;
              }

              if (!pullRequest.maintainerCanModify) {
                console.log(`PR not owned by ${context.repo.owner} and does not have maintainer edits enabled`);

                await github.rest.issues.createComment({
                  issue_number: pullNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "Thanks for submitting a pull request!\n\nIn order to review and merge pull requests most efficiently, we require that all pull requests grant maintainer edit access before we review them. For information on how to do this, [see the relevant GitHub documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). Additionally, GitHub doesn't allow maintainer permissions from organization accounts. Please resubmit this PR from a personal GitHub account with maintainer permissions enabled."
                });

                await github.rest.pulls.update({
                  pull_number: pullNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed'
                });
              }
            } catch(e) {
              console.log(e);
            }
